# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{blitz}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Conway"]
  s.date = %q{2010-04-26}
  s.description = %q{A Rails plugin for feature, view, controller, model, & helper generators. It is meant to be used as part of an "Outside-In" Test-Driven Development cycle.}
  s.email = %q{wr0ngway@yahoo.com}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "CHANGELOG.textile",
     "README.textile",
     "VERSION",
     "generators/controller/controller_generator.rb",
     "generators/controller/templates/controller.rb",
     "generators/feature/feature_generator.rb",
     "generators/feature/templates/feature.feature",
     "generators/feature/templates/step_definition.rb",
     "generators/functional_test/functional_test_generator.rb",
     "generators/functional_test/templates/functional_test.rb",
     "generators/helper/helper_generator.rb",
     "generators/helper/templates/helper.rb",
     "generators/helper/templates/helper_test.rb",
     "generators/model/model_generator.rb",
     "generators/model/templates/factory.rb",
     "generators/model/templates/migration.rb",
     "generators/model/templates/model.rb",
     "generators/model/templates/unit_test.rb",
     "generators/support/generator_helper.rb",
     "generators/support/insert_commands.rb",
     "generators/view/templates/empty.html.erb",
     "generators/view/templates/index.html.erb",
     "generators/view/templates/new.html.erb",
     "generators/view/view_generator.rb",
     "lib/blitz.rb",
     "lib/generators/controller/controller_generator.rb",
     "lib/generators/controller/templates/controller.rb",
     "lib/generators/feature/feature_generator.rb",
     "lib/generators/feature/templates/feature.feature",
     "lib/generators/feature/templates/step_definition.rb",
     "lib/generators/functional_test/functional_test_generator.rb",
     "lib/generators/functional_test/templates/functional_test.rb",
     "lib/generators/helper/helper_generator.rb",
     "lib/generators/helper/templates/helper.rb",
     "lib/generators/helper/templates/helper_test.rb",
     "lib/generators/model/model_generator.rb",
     "lib/generators/model/templates/factory.rb",
     "lib/generators/model/templates/migration.rb",
     "lib/generators/model/templates/model.rb",
     "lib/generators/model/templates/unit_test.rb",
     "lib/generators/support/generator_helper.rb",
     "lib/generators/support/insert_commands.rb",
     "lib/generators/view/templates/empty.html.erb",
     "lib/generators/view/templates/index.html.erb",
     "lib/generators/view/templates/new.html.erb",
     "lib/generators/view/view_generator.rb"
  ]
  s.homepage = %q{http://github.com/wr0ngway/blitz}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A Rails plugin for feature, view, controller, model, & helper generators.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0.0.beta3"])
    else
      s.add_dependency(%q<rails>, [">= 3.0.0.beta3"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0.0.beta3"])
  end
end

